"""
State management for AI Textbook Generator using LangGraph.

This module defines the data contracts (Pydantic models) and state schema (TypedDict)
that all workflow nodes must adhere to. It serves as the single source of truth for
data structures flowing through the system.
"""

import operator
from typing import Any, List, TypedDict, Annotated, Optional
from pydantic import BaseModel, Field


# ============================================================================
# DATA MODELS - Pydantic schemas for structured outputs from LLM
# ============================================================================

class SubSection(BaseModel):
    """
    Atomic unit of content representing a single concept or topic.
    
    Each subsection contains enough information for the Researcher to find
    relevant materials and the Writer to generate focused content.
    """
    title: str = Field(
        description="Title of the subsection (e.g., 'Variables in Python')"
    )
    description: str = Field(
        description="Brief description of what this subsection will cover"
    )
    search_query: str = Field(
        description="Optimized search query for RAG system to retrieve relevant information"
    )
    section_type: str = Field(
        default="concept",
        description=(
            "Type of section — controls target word count:\n"
            "  'intro'    : chapter opening, overview (400-600 words)\n"
            "  'concept'  : core theory and explanation (800-1000 words)\n"
            "  'example'  : worked examples, case studies (600-800 words)\n"
            "  'practice' : exercises, problems, applications (500-700 words)\n"
            "  'summary'  : recap and key takeaways (300-500 words)"
        )
    )


class Chapter(BaseModel):
    """
    Logical grouping of related subsections.
    """
    title: str = Field(
        description="Title of the chapter (e.g., 'Getting Started with Python')"
    )
    subsections: List[SubSection] = Field(
        description="Ordered list of subsections within this chapter"
    )


class CurriculumOutline(BaseModel):
    """
    The master plan: Complete hierarchical structure of the textbook.
    
    Generated by the Planner node and consumed by downstream nodes.
    """
    topic: str = Field(
        description="The main topic of the curriculum"
    )
    chapters: List[Chapter] = Field(
        description="Ordered list of all chapters in the curriculum"
    )


# ============================================================================
# WORD COUNT TARGET MAP
# Maps section_type → (min_words, max_words) for Writer prompt injection
# ============================================================================

SECTION_TYPE_WORD_TARGETS: dict[str, tuple[int, int]] = {
    "intro":    (400,  600),
    "concept":  (800, 1000),
    "example":  (600,  800),
    "practice": (500,  700),
    "summary":  (300,  500),
}

DEFAULT_WORD_TARGET = (700, 900)  # Fallback nếu section_type không hợp lệ


def get_word_target(section_type: str) -> tuple[int, int]:
    """
    Get (min_words, max_words) target for a given section type.
    
    Args:
        section_type: One of 'intro', 'concept', 'example', 'practice', 'summary'
        
    Returns:
        Tuple of (min_words, max_words)
    """
    return SECTION_TYPE_WORD_TARGETS.get(section_type.lower(), DEFAULT_WORD_TARGET)


# ============================================================================
# AGENT STATE - TypedDict schema for LangGraph state management
# ============================================================================

class AgentState(TypedDict):
    """
    Shared state object that flows through all nodes in the LangGraph workflow.
    
    State Evolution:
    1. User provides 'request' + config → Planner generates 'curriculum'
    2. Workflow iterates through chapters/subsections using index trackers
    3. Writer produces 'current_content' → accumulated into 'final_content'
    4. Publisher saves to 'final_filepath'
    """
    
    # ---- Input ----
    request: str        # User's initial request
    
    # ---- User Configuration ----
    num_chapters: int       # Number of chapters to generate (user-controlled, default 3)
    enable_images: bool     # Whether to search and insert images (user-controlled)
    min_words_per_section: int  # Global minimum word floor across all section types
    max_subsections_per_chapter: int  # Max subsections per chapter (user-controlled, default 5)
    
    # ---- Planning ----
    curriculum: Any     # CurriculumOutline after planning; initially None
    
    # ---- Progress Tracking ----
    current_chapter_index: int
    current_subsection_index: int
    
    # ---- Content Management ----
    current_content: str
    final_content: str
    
    # ---- Quality Control ----
    revision_number: int
    review_feedback: str
    
    # ---- Planning outputs ----
    textbook_title: str      # Academic title generated by planner LLM call
    preface_content: str     # Preface markdown (Lời nói đầu) generated by planner

    # ---- RAG ----
    rag_context: str

    # ---- Observability (append-only log) ----
    messages: Annotated[List[str], operator.add]
    
    # ---- Output ----
    final_filepath: Optional[str]


# ============================================================================
# HELPERS
# ============================================================================

def get_chapter_and_subsection(
    curriculum: Any,
    chap_idx: int,
    sub_idx: int
) -> tuple[Any, Any]:
    """
    Unified accessor for curriculum — supports both Pydantic and dict formats.
    
    Returns:
        (chapter, subsection) tuple
        
    Raises:
        IndexError: If indexes are out of bounds
        KeyError: If required fields missing in dict format
    """
    if isinstance(curriculum, CurriculumOutline):
        chapter = curriculum.chapters[chap_idx]
        return chapter, chapter.subsections[sub_idx]
    
    chapter = curriculum['chapters'][chap_idx]
    return chapter, chapter['subsections'][sub_idx]