"""
State management for AI Textbook Generator using LangGraph.

This module defines the data contracts (Pydantic models) and state schema (TypedDict)
that all workflow nodes must adhere to. It serves as the single source of truth for
data structures flowing through the system.
"""

import operator
from typing import Any, List, TypedDict, Annotated, Optional
from pydantic import BaseModel, Field


# ============================================================================
# DATA MODELS - Pydantic schemas for structured outputs from LLM
# ============================================================================
# These models ensure the Planner node always returns valid JSON with proper structure.
# Pydantic provides runtime validation and automatic JSON schema generation for LLMs.


class SubSection(BaseModel):
    """
    Atomic unit of content representing a single concept or topic.
    
    Each subsection contains enough information for the Researcher to find
    relevant materials and the Writer to generate focused content.
    """
    title: str = Field(
        description="Title of the subsection (e.g., 'Variables in Python')"
    )
    description: str = Field(
        description="Brief description of what this subsection will cover"
    )
    search_query: str = Field(
        description="Optimized search query for RAG system to retrieve relevant information"
    )


class Chapter(BaseModel):
    """
    Logical grouping of related subsections.
    
    Chapters provide high-level structure and enable progress tracking
    through the curriculum generation process.
    """
    title: str = Field(
        description="Title of the chapter (e.g., 'Getting Started with Python')"
    )
    subsections: List[SubSection] = Field(
        description="Ordered list of subsections within this chapter"
    )


class CurriculumOutline(BaseModel):
    """
    The master plan: Complete hierarchical structure of the textbook.
    
    Generated by the Planner node and consumed by downstream nodes (Writer, Researcher).
    This acts as the blueprint that guides the entire content generation process.
    """
    topic: str = Field(
        description="The main topic of the curriculum (e.g., 'Python Programming for Beginners')"
    )
    chapters: List[Chapter] = Field(
        description="Ordered list of all chapters in the curriculum"
    )


# ============================================================================
# AGENT STATE - TypedDict schema for LangGraph state management
# ============================================================================
# This defines the "communication protocol" between all nodes in the workflow.
# LangGraph requires state to be a TypedDict with optional Annotated reducers.


class AgentState(TypedDict):
    """
    Shared state object that flows through all nodes in the LangGraph workflow.
    
    State Evolution:
    1. User provides 'request' → Planner generates 'curriculum'
    2. Workflow iterates through chapters/subsections using index trackers
    3. Writer produces 'current_content' → accumulated into 'final_content'
    4. Publisher saves to 'final_filepath'
    
    The 'messages' field uses operator.add as a reducer, meaning each node appends
    to the log rather than overwriting it, providing full audit trail.
    """
    
    # ---- Input ----
    request: str  # User's initial request (e.g., "Create a Python textbook")
    
    # ---- Planning ----
    curriculum: Any  # CurriculumOutline after planning; initially None (use Any to avoid validation errors)
    
    # ---- Progress Tracking ----
    current_chapter_index: int      # Zero-based index of the chapter being processed
    current_subsection_index: int   # Zero-based index of the subsection being processed
    
    # ---- Content Management ----
    current_content: str   # Content generated for the current subsection (temporary buffer)
    final_content: str     # Accumulated final content of all completed subsections
    
    # ---- Quality Control ----
    revision_number: int   # Counter to prevent infinite revision loops (max iterations safeguard)
    review_feedback: str
    # ---- Observability ----
    # Annotated with operator.add: Each node appends messages instead of overwriting
    # This creates an append-only log of all agent actions for debugging and monitoring
    rag_context: str
    messages: Annotated[List[str], operator.add]
    
    # ---- Output ----
    final_filepath: Optional[str]  # Path to generated file; None until publishing completes
    
def get_chapter_and_subsection(
    curriculum: Any,
    chap_idx: int,
    sub_idx: int
) -> tuple[Any, Any]:
    """
    Unified accessor for curriculum — supports both Pydantic and dict formats.
    
    Returns:
        (chapter, subsection) tuple
        
    Raises:
        IndexError: If indexes are out of bounds
        KeyError: If required fields missing in dict format
    """
    if isinstance(curriculum, CurriculumOutline):
        chapter = curriculum.chapters[chap_idx]
        return chapter, chapter.subsections[sub_idx]
    
    # Dict fallback
    chapter = curriculum['chapters'][chap_idx]
    return chapter, chapter['subsections'][sub_idx]    