"""
State management for AI Textbook Generator using LangGraph.

This module defines the data contracts (Pydantic models) and state schema (TypedDict)
that all workflow nodes must adhere to. It serves as the single source of truth for
data structures flowing through the system.

Contents:
    Data models   — Pydantic schemas for structured LLM outputs (SubSection, Chapter,
                    CurriculumOutline). These enforce type safety on Planner output
                    before it enters the graph.
    Char targets  — SECTION_TYPE_CHAR_TARGETS map + get_char_target() accessor.
                    Single source of truth for section length targets consumed by
                    Writer (prompt injection) and Reviewer (quality gate).
    AgentState    — LangGraph TypedDict defining every field that flows through
                    the workflow. All nodes read from and write partial updates to
                    this shared state object.
    Helpers       — Utility functions shared across multiple agent nodes:
                    get_chapter_and_subsection(), clean_section_title(),
                    build_initial_state().
"""

import operator
import re
from typing import Any, List, TypedDict, Annotated, Optional
from pydantic import BaseModel, Field


# ============================================================================
# DATA MODELS — Pydantic schemas for structured LLM outputs
#
# These models are used as `with_structured_output()` targets for the Planner
# and as runtime type guards in agent nodes (isinstance checks).
# ============================================================================

class SubSection(BaseModel):
    """
    Atomic unit of content: a single concept or topic within a chapter.

    Each subsection carries enough metadata for:
    - Researcher: `search_query` drives RAG retrieval
    - Writer:     `section_type` controls prose depth and char target
    - Reviewer:   `description` provides the quality evaluation baseline
    """

    title: str = Field(
        description="Title of the subsection (e.g., 'Variables in Python')"
    )
    description: str = Field(
        description="Brief description of what this subsection will cover"
    )
    search_query: str = Field(
        description="Optimized search query for RAG system to retrieve relevant information"
    )
    section_type: str = Field(
        default="medium",
        description=(
            "Depth level of the section — controls target character count:\n"
            "  'light'   : orientation, recap, bridge sections (1500-2500 chars)\n"
            "  'medium'  : explanations, demonstrations, illustrations (3000-4500 chars)\n"
            "  'deep'    : theory, analysis, complex techniques (4500-6500 chars)\n"
            "  'applied' : exercises, hands-on tasks, practice drills (2500-3500 chars)"
        )
    )


class Chapter(BaseModel):
    """
    Logical grouping of related subsections forming one textbook chapter.
    """

    title: str = Field(
        description="Title of the chapter (e.g., 'Getting Started with Python')"
    )
    subsections: List[SubSection] = Field(
        description="Ordered list of subsections within this chapter"
    )


class CurriculumOutline(BaseModel):
    """
    Master plan: complete hierarchical structure of the textbook.

    Generated by the Planner node as the first output of the workflow.
    Consumed by every downstream node (Researcher, Writer, Reviewer,
    Illustrator) to locate the current chapter and subsection.
    """

    topic: str = Field(
        description="The main topic of the curriculum"
    )
    chapters: List[Chapter] = Field(
        description="Ordered list of all chapters in the curriculum"
    )


# ============================================================================
# CHARACTER COUNT TARGET MAP
#
# Maps section_type → (min_chars, max_chars).
# Unit: characters (not words) — language-agnostic, correct for Vietnamese.
#
# These values are the single source of truth used by:
#   - Writer:    injected into system prompt as <char_target> + RULE 2.5
#   - Reviewer:  quality gate checks polished content against these floors
#   - write_section node: applies user min_chars_per_section floor on top
# ============================================================================

SECTION_TYPE_CHAR_TARGETS: dict[str, tuple[int, int]] = {
    "light":   (1500, 2500),   # Orientation, recap, bridge, intro sections
    "medium":  (3000, 4500),   # Explanations, demonstrations, illustrations
    "deep":    (4500, 6500),   # Theory, analysis, complex techniques
    "applied": (2500, 3500),   # Exercises, hands-on tasks, practice drills
}

# Fallback used when section_type is missing or not one of the four valid values
DEFAULT_CHAR_TARGET = (3000, 4500)

# ============================================================================
# CONTENT LEVEL SCALE FACTORS
#
# User-facing levels that scale all section_type char targets proportionally.
# Applied as a multiplier on top of SECTION_TYPE_CHAR_TARGETS.
#
#   "Ngắn"      → 0.55x  — concise, key concepts only
#   "Trung Bình" → 1.0x  — default, balanced depth
#   "Dài"       → 1.6x  — thorough, more examples
#   "Rất Dài"   → 2.3x  — comprehensive, academic depth
# ============================================================================

CONTENT_LEVEL_SCALES: dict[str, float] = {
    "Ngắn":       0.55,
    "Trung Bình": 1.0,
    "Dài":        1.6,
    "Rất Dài":    2.3,
}

DEFAULT_CONTENT_LEVEL = "Trung Bình"


def get_char_target(
    section_type: str,
    content_level: str = DEFAULT_CONTENT_LEVEL,
) -> tuple[int, int]:
    """
    Return (min_chars, max_chars) scaled by content_level.

    Args:
        section_type:  One of 'light', 'medium', 'deep', 'applied'.
        content_level: One of 'Ngắn', 'Trung Bình', 'Dài', 'Rất Dài'.

    Returns:
        (min_chars, max_chars) tuple, rounded to nearest 50.
    """
    base_min, base_max = SECTION_TYPE_CHAR_TARGETS.get(
        section_type.lower(), DEFAULT_CHAR_TARGET
    )
    scale = CONTENT_LEVEL_SCALES.get(content_level, 1.0)

    scaled_min = int(round(base_min * scale / 50) * 50)
    scaled_max = int(round(base_max * scale / 50) * 50)

    # Ensure max > min with meaningful gap
    scaled_max = max(scaled_max, scaled_min + 500)
    return scaled_min, scaled_max

# ============================================================================
# AGENT STATE — LangGraph TypedDict
#
# This is the shared mutable state object that flows through every node.
# Nodes return partial dicts; LangGraph merges them into the running state.
#
# State evolution across the workflow:
#   1. User provides 'request' + config fields → build_initial_state()
#   2. Ingester populates ChromaDB (no state fields written)
#   3. Planner writes: curriculum, textbook_title, preface_content
#   4. Per-subsection loop:
#        Researcher → rag_context
#        Writer     → current_content, chapter_header_written
#        Reviewer   → current_content (polished), review_feedback, revision_number
#        Illustrator→ current_content (with images)
#        Checkpoint → final_content (accumulated), indexes advanced
#   5. Publisher writes: final_filepath
# ============================================================================

class AgentState(TypedDict):
    """
    Shared state object flowing through all nodes in the LangGraph workflow.

    Field groups:
        Input           — user request string
        Configuration   — user-controlled generation parameters
        Planning        — curriculum outline + generated title/preface
        Progress        — chapter/subsection index trackers
        Content         — per-subsection buffer + accumulated document
        Quality control — revision counter, feedback string, header flag
        RAG             — retrieved context for current subsection
        Observability   — append-only message log (reducer: operator.add)
        Output          — path to the final generated file
    """

    # ---- Input ----
    request: str
    """User's initial topic request (e.g. 'Học máy')."""

    # ---- User Configuration ----
    num_chapters: int
    """Number of chapters to generate. Passed to Planner. Default: 3."""

    enable_images: bool
    """Whether to search and insert images via Serper/DALL-E. Default: True."""

    min_chars_per_section: int
    """
    Global minimum character floor applied on top of section_type defaults.
    Writer uses max(section_type_min, this_floor) as the effective minimum.
    Set to 0 to use section_type defaults unchanged.
    """

    max_subsections_per_chapter: int
    """Upper bound on subsections per chapter passed to Planner. Default: 5."""

    # ---- Planning ----
    curriculum: Any
    """
    CurriculumOutline Pydantic object after planning; None before Planner runs.
    Accessed by all downstream nodes via get_chapter_and_subsection().
    """

    # ---- Progress Tracking ----
    current_chapter_index: int
    """0-indexed position of the chapter currently being written."""

    current_subsection_index: int
    """0-indexed position within current_chapter_index's subsection list."""

    # ---- Content Management ----
    current_content: str
    """
    Per-subsection content buffer. Written by Writer, polished by Reviewer,
    illustrated by Illustrator. Accumulated into final_content at checkpoints.
    """

    final_content: str
    """
    Accumulated document body. Checkpoint nodes append current_content here
    and clear current_content. Publisher merges this with the last
    current_content (which bypasses the checkpoint) to form the complete doc.
    """

    # ---- Quality Control ----
    revision_number: int
    """
    Number of revision attempts for the current subsection.
    Reset to 0 at each checkpoint. Reviewer increments it on rejection.
    Graph-level ceiling enforced in route_after_review() (graph.py).
    """

    review_feedback: str
    """
    Non-empty string → Reviewer rejected the draft; feedback describes issues.
    Empty string → content approved; workflow advances to Illustrator.
    Cleared to "" by Reviewer on approval or when max revisions reached.
    """

    chapter_header_written: bool
    """
    True after Writer emits the `# CHƯƠNG N` heading for the current chapter.
    Prevents duplicate chapter headers across subsections in the same chapter.
    Reset to False only by append_and_update_chapter (checkpoint node).
    """

    # ---- Planning Outputs ----
    textbook_title: str
    """Formal academic title generated by Planner (e.g. 'Giáo trình Học máy')."""

    preface_content: str
    """
    Lời nói đầu markdown generated by Planner.
    Prepended to the document body in publish_curriculum().
    """

    # ---- RAG ----
    rag_context: str
    """
    Retrieved document chunks for the current subsection.
    Written by Researcher, consumed by Writer.
    Reset between subsections (Researcher overwrites on each iteration).
    """

    # ---- Observability ----
    messages: Annotated[List[str], operator.add]
    """
    Append-only log of workflow milestones and status messages.
    The operator.add reducer means nodes append by returning
    {"messages": ["new message"]} — never by overwriting the full list.
    """

    # ---- Output ----
    final_filepath: Optional[str]
    """
    Path to the generated file (PDF if pypandoc succeeded, .md otherwise).
    None until Publisher completes.
    """
    content_level: str
    """
    User-selected content depth level. Controls char targets across all
    section types via CONTENT_LEVEL_SCALES multiplier.
    One of: 'Ngắn', 'Trung Bình', 'Dài', 'Rất Dài'. Default: 'Trung Bình'.
    """
    # ---- Export ----
    export_formats: List[str]
    """
    List of output formats requested by user.
    Valid values: "PDF", "Word". Both can be selected simultaneously.
    Publisher generates only the formats present in this list.
    """

    final_docx_filepath: Optional[str]
    """
    Path to the generated .docx file, or None if Word export was not
    requested or failed.
    """
    # ---- Validation ----
    validation_failed:     bool
    validation_reason:     str
    validation_suggestion: str

# ============================================================================
# HELPERS — shared utility functions used across multiple agent nodes
# ============================================================================

def get_chapter_and_subsection(
    curriculum: Any,
    chap_idx: int,
    sub_idx: int,
) -> tuple[Any, Any]:
    """
    Unified curriculum accessor supporting both Pydantic and dict formats.

    Pydantic format (CurriculumOutline) is the standard runtime format.
    Dict format is supported for unit tests and compatibility with any
    code path that constructs curriculum manually.

    Args:
        curriculum: CurriculumOutline instance or equivalent dict.
        chap_idx:   0-indexed chapter position.
        sub_idx:    0-indexed subsection position within the chapter.

    Returns:
        (chapter, subsection) tuple — types match the input format
        (Chapter/SubSection Pydantic objects, or plain dicts).

    Raises:
        IndexError: If either index is out of bounds.
        KeyError:   If required keys are missing in dict format.
    """
    if isinstance(curriculum, CurriculumOutline):
        chapter = curriculum.chapters[chap_idx]
        return chapter, chapter.subsections[sub_idx]

    chapter = curriculum['chapters'][chap_idx]
    return chapter, chapter['subsections'][sub_idx]


def clean_section_title(title: str) -> str:
    """
    Strip structured prefixes from LLM-generated section titles.

    The Planner LLM occasionally produces titles of the form:
        "Mục 1.2: Tên thật"   →  "Tên thật"
        "Phần 3: Nội dung"    →  "Nội dung"
        "Bài 2.1: Tiêu đề"    →  "Tiêu đề"

    The regex only matches when the prefix is a keyword followed by a
    numeric index (e.g. "Mục 1.2"), NOT mid-sentence usage like
    "Bài toán tối ưu hóa:" which would otherwise be incorrectly stripped.

    Used by: Writer node, Reviewer node.

    Args:
        title: Raw section title string from curriculum.

    Returns:
        Cleaned title with prefix stripped, or the original string unchanged
        if the pattern does not match.
    """
    return re.sub(r'^(Mục|Phần|Bài)\s+[\d.]+\s*:\s*', '', title).strip()


def build_initial_state(
    request: str,
    num_chapters: int = 3,
    enable_images: bool = True,
    min_chars_per_section: int = 0,
    max_subsections_per_chapter: int = 5,
    content_level: str = "Trung Bình",
    export_formats: list | None = None,
    
) -> dict:
    """
    Factory function for constructing the initial AgentState dict.

    Always use this instead of constructing state dicts manually at call sites.
    Ensures every required field is present with a validated default, preventing
    KeyError or None-type failures in downstream agent nodes that call
    state.get(...) without a fallback.

    TypedDict does not support default values by design — this factory is the
    idiomatic pattern for LangGraph state initialisation.

    Args:
        request:                    User's textbook topic (required).
        num_chapters:               Number of chapters to generate. Default: 3.
        enable_images:              Whether to insert images. Default: True.
        min_chars_per_section:      Global char floor across all section types.
                                    0 = use section_type defaults unchanged.
        max_subsections_per_chapter: Upper bound on subsections per chapter.
                                    Default: 5.

    Returns:
        Dict conforming to the AgentState TypedDict schema with all fields
        initialised to safe zero/empty values.
    """
    return {
        # Input
        "request": request,
        # Configuration
        "num_chapters": num_chapters,
        "enable_images": enable_images,
        "min_chars_per_section": min_chars_per_section,
        "max_subsections_per_chapter": max_subsections_per_chapter,
        # Planning — populated by Planner node
        "curriculum": None,
        "textbook_title": "",
        "preface_content": "",
        # Progress — reset to 0 at start and by checkpoint nodes
        "current_chapter_index": 0,
        "current_subsection_index": 0,
        # Content — buffers cleared at each checkpoint
        "current_content": "",
        "final_content": "",
        # Quality control
        "revision_number": 0,
        "review_feedback": "",
        "chapter_header_written": False,
        "content_level": content_level,
        # RAG — overwritten by Researcher on each subsection iteration
        "rag_context": "",
        # Observability — append-only, starts empty
        "messages": [],
        # Output — set by Publisher
        "final_filepath": None,
        "export_formats":       export_formats or ["Word"],
        "final_docx_filepath":  None,
        # ---- Validation ----
        "validation_failed":     False,
        "validation_reason":     "",
        "validation_suggestion": ""
    }