"""add curriculum json

Revision ID: 084c96af4337
Revises: 45665cd98e48
Create Date: 2026-05-04 15:17:28.358148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '084c96af4337'
down_revision: Union[str, None] = '45665cd98e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textbooks', sa.Column('curriculum_json', sa.JSON(), nullable=True))
    op.add_column('textbooks', sa.Column('total_chapters', sa.Integer(), nullable=True))
    op.add_column('textbooks', sa.Column('total_subsections', sa.Integer(), nullable=True))
    op.alter_column('textbooks', 'user_requirements',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('textbooks', 'content_level',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('textbooks', 'max_subsections_per_chapter',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('textbooks', 'max_subsections_per_chapter',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('textbooks', 'content_level',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('textbooks', 'user_requirements',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.drop_column('textbooks', 'total_subsections')
    op.drop_column('textbooks', 'total_chapters')
    op.drop_column('textbooks', 'curriculum_json')
    # ### end Alembic commands ###
