"""add_progress_data_to_textbooks

Revision ID: 1353ebcf0cd0
Revises: 
Create Date: 2026-04-29 17:19:15.911406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1353ebcf0cd0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textbooks', sa.Column('progress_data', sa.JSON(), nullable=True))
    op.drop_index('idx_textbooks_content_type', table_name='textbooks')
    op.create_index(op.f('ix_textbooks_content_type'), 'textbooks', ['content_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_textbooks_content_type'), table_name='textbooks')
    op.create_index('idx_textbooks_content_type', 'textbooks', ['content_type'], unique=False)
    op.drop_column('textbooks', 'progress_data')
    # ### end Alembic commands ###
