"""
State management for AI Textbook Generator using LangGraph.

This module defines the data contracts (Pydantic models) and state schema (TypedDict)
that all workflow nodes must adhere to. It serves as the single source of truth for
data structures flowing through the system.

Contents:
    Data models   — Pydantic schemas for structured LLM outputs (SubSection, Chapter,
                    CurriculumOutline). These enforce type safety on Planner output
                    before it enters the graph.
    Char targets  — SECTION_TYPE_CHAR_TARGETS map + get_char_target() accessor.
                    Single source of truth for section length targets consumed by
                    Writer (prompt injection) and Reviewer (quality gate).
    AgentState    — LangGraph TypedDict defining every field that flows through
                    the workflow. All nodes read from and write partial updates to
                    this shared state object.
    Helpers       — Utility functions shared across multiple agent nodes:
                    get_chapter_and_subsection(), clean_section_title(),
                    build_initial_state().
"""

import operator
import re
from typing import Any, List, TypedDict, Annotated, Optional
from pydantic import BaseModel, Field


# ============================================================================
# DATA MODELS — Pydantic schemas for structured LLM outputs
# ============================================================================

class SubSection(BaseModel):
    """
    Atomic unit of content: a single concept or topic within a chapter.

    Each subsection carries enough metadata for:
    - Researcher: `search_query` drives RAG retrieval
    - Writer:     `section_type` controls prose depth and char target
    - Reviewer:   `description` provides the quality evaluation baseline
    """

    title: str = Field(
        description="Title of the subsection (e.g., 'Variables in Python')"
    )
    description: str = Field(
        description="Brief description of what this subsection will cover"
    )
    search_query: str = Field(
        description="Optimized search query for RAG system to retrieve relevant information"
    )
    section_type: str = Field(
        default="medium",
        description=(
            "Depth level of the section — controls target character count:\n"
            "  'light'   : orientation, recap, bridge sections (1500-2500 chars)\n"
            "  'medium'  : explanations, demonstrations, illustrations (3000-4500 chars)\n"
            "  'deep'    : theory, analysis, complex techniques (4500-6500 chars)\n"
            "  'applied' : exercises, hands-on tasks, practice drills (2500-3500 chars)"
        )
    )


class Chapter(BaseModel):
    """
    Logical grouping of related subsections forming one textbook chapter.
    """

    title: str = Field(
        description="Title of the chapter (e.g., 'Getting Started with Python')"
    )
    subsections: List[SubSection] = Field(
        description="Ordered list of subsections within this chapter"
    )


class CurriculumOutline(BaseModel):
    """
    Master plan: complete hierarchical structure of the textbook.

    Generated by the Planner node as the first output of the workflow.
    Consumed by every downstream node (Researcher, Writer, Reviewer,
    Illustrator) to locate the current chapter and subsection.
    """

    topic: str = Field(
        description="The main topic of the curriculum"
    )
    chapters: List[Chapter] = Field(
        description="Ordered list of all chapters in the curriculum"
    )


# ============================================================================
# CHARACTER COUNT TARGET MAP
#
# Maps section_type → (min_chars, max_chars).
# Unit: characters (not words) — language-agnostic, correct for Vietnamese.
# ============================================================================

SECTION_TYPE_CHAR_TARGETS: dict[str, tuple[int, int]] = {
    "light":   (1500, 2500),
    "medium":  (3000, 4500),
    "deep":    (4500, 6500),
    "applied": (2500, 3500),
}

DEFAULT_CHAR_TARGET = (3000, 4500)

# ============================================================================
# CONTENT LEVEL SCALE FACTORS
# ============================================================================

CONTENT_LEVEL_SCALES: dict[str, float] = {
    "Ngắn":       0.55,
    "Trung Bình": 1.0,
    "Dài":        1.6,
    "Rất Dài":    2.3,
}

DEFAULT_CONTENT_LEVEL = "Trung Bình"
CONTENT_LEVEL_MIN_WORD_DEFAULTS: dict[str, int] = {
    "Ngắn": 300,
    "Trung Bình": 500,
    "Dài": 800,
    "Rất Dài": 1200,
}
CONTENT_LEVEL_MAX_WORD_DEFAULTS: dict[str, int] = {
    "Ngắn": 500,
    "Trung Bình": 800,
    "Dài": 1200,
    "Rất Dài": 1500,
}
CONTENT_LEVEL_MIN_WORD_KEYS: dict[str, str] = {
    "Ngắn": "CONTENT_LEVEL_SHORT_MIN_WORDS",
    "Trung Bình": "CONTENT_LEVEL_MEDIUM_MIN_WORDS",
    "Dài": "CONTENT_LEVEL_LONG_MIN_WORDS",
    "Rất Dài": "CONTENT_LEVEL_VERY_LONG_MIN_WORDS",
}
CONTENT_LEVEL_MAX_WORD_KEYS: dict[str, str] = {
    "Ngắn": "CONTENT_LEVEL_SHORT_MAX_WORDS",
    "Trung Bình": "CONTENT_LEVEL_MEDIUM_MAX_WORDS",
    "Dài": "CONTENT_LEVEL_LONG_MAX_WORDS",
    "Rất Dài": "CONTENT_LEVEL_VERY_LONG_MAX_WORDS",
}
CONTENT_WORD_TO_CHAR_RATIO_DEFAULTS: dict[str, float] = {
    "vi": 5.0,
    "en": 6.0,
}
CONTENT_WORD_TO_CHAR_RATIO_KEYS: dict[str, str] = {
    "vi": "CONTENT_WORD_TO_CHAR_RATIO_VI",
    "en": "CONTENT_WORD_TO_CHAR_RATIO_EN",
}


def _runtime_config_value(
    key: str,
    default: Any,
    advanced_config: dict[str, Any] | None = None,
) -> Any:
    if advanced_config and key in advanced_config:
        return advanced_config[key]
    try:
        from app.services.runtime_config import get_runtime_config

        value = get_runtime_config(key, required=False)
    except Exception:
        value = None
    return default if value is None else value


def _runtime_int(
    key: str,
    default: int,
    advanced_config: dict[str, Any] | None = None,
) -> int:
    try:
        return max(0, int(_runtime_config_value(key, default, advanced_config)))
    except (TypeError, ValueError):
        return default


def _runtime_float(
    key: str,
    default: float,
    advanced_config: dict[str, Any] | None = None,
) -> float:
    try:
        value = float(_runtime_config_value(key, default, advanced_config))
    except (TypeError, ValueError):
        return default
    return value if value > 0 else default


def _runtime_content_level_words(
    content_level: str,
    word_keys: dict[str, str],
    word_defaults: dict[str, int],
    advanced_config: dict[str, Any] | None = None,
) -> int:
    key = word_keys.get(content_level)
    default = word_defaults.get(content_level, 0)
    if not key:
        return default
    return _runtime_int(key, default, advanced_config)


def _runtime_word_to_char_ratio(
    language: str,
    advanced_config: dict[str, Any] | None = None,
) -> float:
    lang = (language or "vi").lower()
    if lang.startswith("en"):
        lang = "en"
    else:
        lang = "vi"
    key = CONTENT_WORD_TO_CHAR_RATIO_KEYS[lang]
    default = CONTENT_WORD_TO_CHAR_RATIO_DEFAULTS[lang]
    return _runtime_float(key, default, advanced_config)


def _words_to_chars(words: int, ratio: float) -> int:
    return int(round((words * ratio) / 50) * 50)


def get_char_target(
    section_type: str,
    content_level: str = DEFAULT_CONTENT_LEVEL,
    advanced_config: dict[str, Any] | None = None,
    language: str = "vi",
) -> tuple[int, int]:
    """
    Return (min_chars, max_chars) scaled by content_level.

    Args:
        section_type:  One of 'light', 'medium', 'deep', 'applied'.
        content_level: One of 'Ngắn', 'Trung Bình', 'Dài', 'Rất Dài'.
        language:      'vi' or 'en'; controls word-to-character conversion.

    Returns:
        (min_chars, max_chars) tuple, rounded to nearest 50.
    """
    base_min, base_max = SECTION_TYPE_CHAR_TARGETS.get(
        section_type.lower(), DEFAULT_CHAR_TARGET
    )
    scale = CONTENT_LEVEL_SCALES.get(content_level, 1.0)

    scaled_min = int(round(base_min * scale / 50) * 50)
    scaled_max = int(round(base_max * scale / 50) * 50)
    ratio = _runtime_word_to_char_ratio(language, advanced_config)
    min_words = _runtime_content_level_words(
        content_level,
        CONTENT_LEVEL_MIN_WORD_KEYS,
        CONTENT_LEVEL_MIN_WORD_DEFAULTS,
        advanced_config,
    )
    max_words = _runtime_content_level_words(
        content_level,
        CONTENT_LEVEL_MAX_WORD_KEYS,
        CONTENT_LEVEL_MAX_WORD_DEFAULTS,
        advanced_config,
    )

    if min_words:
        word_floor_chars = _words_to_chars(min_words, ratio)
        scaled_min = max(scaled_min, word_floor_chars)

    if max_words:
        if min_words and max_words < min_words:
            max_words = min_words
        word_ceiling_chars = _words_to_chars(max_words, ratio)
        scaled_max = min(scaled_max, max(word_ceiling_chars, scaled_min + 250))

    scaled_max = max(scaled_max, scaled_min + 250)
    return scaled_min, scaled_max


# ============================================================================
# AGENT STATE — LangGraph TypedDict
# ============================================================================

class AgentState(TypedDict):
    """
    Shared state object flowing through all nodes in the LangGraph workflow.

    Field groups:
        Input           — user request string
        Identity        — core topic and requirements extracted by Validator
        Configuration   — user-controlled generation parameters
        Planning        — curriculum outline + generated title/preface
        HitL Gate       — curriculum confirmation flag for Human-in-the-Loop
        Progress        — chapter/subsection index trackers
        Content         — per-subsection buffer + accumulated document
        Quality control — revision counter, feedback string, header flag
        RAG             — retrieved context for current subsection
        CRAG Pipeline   — query formulation, retrieval scoring, web supplement
        Dynamic Routing — rejection type classification for True Dynamic Routing
        Observability   — append-only message log (reducer: operator.add)
        Output          — path to the final generated file
        Validation      — topic validation results
       
    """

    # ---- Input ----
    request: str

    # ---- Identity (extracted by Validator; consumed by Ingester + Researcher) ----
    core_topic: str
    """
    Core subject distilled from the raw user request by the Validator node.
    Example: request='Machine Learning với ví dụ code' → core_topic='Machine Learning'
    Drives ingestion query expansion and researcher query enhancement.
    """
    user_requirements: str
    """
    Optional user requirements extracted from the raw request by the Validator.
    Example: 'với ví dụ code và ứng dụng thực tế'
    Injected into Researcher queries and Writer prompts to fulfil user expectations.
    Empty string when no additional requirements were specified.
    """

    # ---- User Configuration ----
    num_chapters: int
    enable_images: bool
    min_chars_per_section: int
    max_subsections_per_chapter: int
    language: str
    textbook_mode: str
    advanced_config: dict[str, Any]

    # ---- Planning ----
    curriculum: Any
    initial_curriculum_structure: Optional[dict[str, Any]]
    planning_mode: str

    # ---- Human-in-the-Loop Gate (Target 3) ----
    curriculum_confirmed: bool
    """
    Set to True by the HitL gate node once the user explicitly approves
    the generated curriculum. Remains False during planning-only workflows.
    Guards the conditional edge that separates planning from content generation:
        False → wait / END (planning workflow)
        True  → proceed to ingestion + content loop
    """

    # ---- Progress Tracking ----
    current_chapter_index: int
    current_subsection_index: int

    # ---- Content Management ----
    current_content: str
    final_content: str

    # ---- Quality Control ----
    revision_number: int
    review_feedback: str
    chapter_header_written: bool

    # ---- Planning Outputs ----
    textbook_title: str
    preface_content: str

    # ---- RAG ----
    rag_context: str
    rag_collection_name: str
    """
    Per-textbook ChromaDB collection name. Keeping each run in its own
    collection prevents locked/deleted directories or prior runs from leaking
    stale chunks into the current textbook.
    """
    rag_source_audit: dict[str, Any]
    """
    Compact source audit summary for UI progress polling. Contains source
    URLs/domains/counts/query metadata, never full chunk content.
    """
    rag_best_effort_context: str
    rag_best_effort_audit: dict[str, Any]
    rag_best_effort_score: float

    # ---- CRAG Pipeline (Target 1) ----
    retrieval_query: str
    """
    The fully-formed ChromaDB search query produced by QueryFormulator.
    Passed to RetrieverNode as its sole input, then logged for audit.
    Reset to '' at the start of each subsection by the checkpoint nodes.
    """
    context_quality: str
    """
    Evaluation result written by ContextEvaluator after scoring retrieved chunks.
    Valid values:
        'sufficient'   — RAG context is rich enough; proceed to ContentWriter
        'insufficient' — context too sparse; trigger web_supplement fetch before writing
    Default: 'sufficient' (skip supplemental fetch when CRAG nodes are inactive).
    """
    web_supplement_context: str
    """
    Additional context fetched from live web sources by ContextEvaluator when
    context_quality == 'insufficient'. Appended to rag_context before ContentWriter runs.
    Empty string in the common case where RAG context is sufficient.
    """

    # ---- Observability ----
    messages: Annotated[List[str], operator.add]

    # ---- Output ----
    # Compatibility alias for the PDF path. It must never contain DOCX/Markdown.
    final_filepath: Optional[str]
    final_markdown_filepath: Optional[str]
    final_pdf_filepath: Optional[str]
    partial_markdown_filepath: Optional[str]
    content_level: str

    # ---- Export ----
    export_formats: List[str]
    final_docx_filepath: Optional[str]
    export_errors: dict[str, str]

    # ---- Validation ----
    validation_failed:     bool
    """True when validator node rejects the topic — routes graph to END."""
    validation_reason:     str
    """Localized explanation of why the topic was rejected."""
    validation_suggestion: str
    """Pipe-separated list of more specific topic alternatives."""

    content_type: str  # "scholarly" | "technical" | "practical" | "lifestyle"
    # ---- True Dynamic Routing (Target 2) ----
    rejection_type: Optional[str]
    """
    Rejection classification produced by the Reviewer quality gate.
    Used by route_after_review() to select the correct remediation path:
        'missing_context' — RAG context was insufficient; re-route to QueryFormulator
                            (triggers a fresh retrieval cycle, not just a rewrite)
        'formatting_error'— Content has correct information but poor structure/format;
                            re-route directly to ContentWriter with targeted instructions
        None              — Content approved; proceed to Illustrator
    Reset to None at each subsection checkpoint.
    """

    used_rag_queries: List[str]   # accumulate across revision attempts
    rag_retrieval_attempts: int
    rag_recovery_attempted: bool
    """
    Number of main RetrieverNode attempts for the current subsection.
    Evaluator tool-call queries remain in used_rag_queries for audit, but
    they should not consume the router's primary retry budget.
    """
    # ---- Preview (Phase 5) ----
  
    section_summaries: List[str]
    """
    Ordered list of one-line summaries for each completed subsection.
    Injected into Writer's context retrieval and content generation calls
    to prevent repetition and ensure logical progression across sections.
    Format per entry: "Mục X.Y 'Title': <prose preview>..."
    Populated by checkpoint nodes after Reviewer approves each section.
    """

# ============================================================================
# HELPERS
# ============================================================================

def get_chapter_and_subsection(
    curriculum: Any,
    chap_idx: int,
    sub_idx: int,
) -> tuple[Any, Any]:
    """
    Unified curriculum accessor supporting both Pydantic and dict formats.

    Args:
        curriculum: CurriculumOutline instance or equivalent dict.
        chap_idx:   0-indexed chapter position.
        sub_idx:    0-indexed subsection position within the chapter.

    Returns:
        (chapter, subsection) tuple.

    Raises:
        IndexError: If either index is out of bounds.
        KeyError:   If required keys are missing in dict format.
    """
    if isinstance(curriculum, CurriculumOutline):
        chapter = curriculum.chapters[chap_idx]
        return chapter, chapter.subsections[sub_idx]

    chapter = curriculum['chapters'][chap_idx]
    return chapter, chapter['subsections'][sub_idx]


def clean_section_title(title: str) -> str:
    """
    Strip structured prefixes from LLM-generated section titles.

    Handles patterns like:
        "Mục 1.2: Tên thật"   →  "Tên thật"
        "Phần 3: Nội dung"    →  "Nội dung"
        "Bài 2.1: Tiêu đề"    →  "Tiêu đề"

    Args:
        title: Raw section title string from curriculum.

    Returns:
        Cleaned title with prefix stripped, or original if no match.
    """
    return re.sub(
        r'^(Mục|Phần|Bài|Section|Chapter|Part|Lesson)\s+[\d.]+\s*:\s*',
        '',
        title,
        flags=re.IGNORECASE,
    ).strip()


def build_initial_state(
    request: str,
    num_chapters: int = 3,
    enable_images: bool = True,
    min_chars_per_section: int = 0,
    max_subsections_per_chapter: int = 5,
    content_level: str = "Trung Bình",
    content_type: str = "technical",
    textbook_mode: str = "standard",
    core_topic: str = "",
    user_requirements: str = "",
    language: str = "vi",
    advanced_config: dict[str, Any] | None = None,
    initial_curriculum_structure: dict[str, Any] | None = None,
    planning_mode: str = "auto",
    section_summaries: list = None, #type: ignore
    export_formats: list | None = None,
) -> dict:
    """
    Factory function for constructing the initial AgentState dict.

    Always use this instead of constructing state dicts manually at call sites.
    Ensures every required field is present with a validated default.

    Args:
        request:                     User's raw textbook topic string (required).
        num_chapters:                Number of chapters to generate.
        enable_images:               Whether to insert images.
        min_chars_per_section:       Global char floor across all section types.
        max_subsections_per_chapter: Upper bound on subsections per chapter.
        content_level:               One of 'Ngắn', 'Trung Bình', 'Dài', 'Rất Dài'.
        content_type:                One of 'scholarly'|'technical'|'practical'|'lifestyle'.
        core_topic:                  Core subject extracted by Validator (defaults to request).
        user_requirements:           Optional requirements extracted by Validator.
        advanced_config:             Effective user/system config snapshot for this workflow run.
        section_summaries:           Pre-populated summaries list (for resume flows).
        export_formats:              List of export formats ('PDF', 'Word').

    Returns:
        Dict conforming to the AgentState TypedDict schema.
    """
    return {
        # ---- Input ----
        "request": request,
        # ---- Identity ----
        "core_topic":         core_topic or request,  # fall back to raw request if not extracted
        "user_requirements":  user_requirements,
        # ---- Configuration ----
        "num_chapters":                num_chapters,
        "enable_images":               enable_images,
        "min_chars_per_section":       min_chars_per_section,
        "max_subsections_per_chapter": max_subsections_per_chapter,
        "content_type":                content_type,
        "textbook_mode":               textbook_mode,
        "language":                    language,
        "advanced_config":             advanced_config or {},
        # ---- Planning ----
        "curriculum":      None,
        "initial_curriculum_structure": initial_curriculum_structure,
        "planning_mode": planning_mode,
        "textbook_title":  "",
        "preface_content": "",
        # ---- HitL Gate ----
        "curriculum_confirmed": False,
        # ---- Progress ----
        "current_chapter_index":    0,
        "current_subsection_index": 0,
        # ---- Content ----
        "current_content": "",
        "final_content":   "",
        # ---- Quality Control ----
        "revision_number":        0,
        "review_feedback":        "",
        "chapter_header_written": False,
        "content_level":          content_level,
        # ---- RAG ----
        "rag_context":          "",
        "rag_collection_name":  "dynamic_context",
        "rag_source_audit":     {},
        "rag_best_effort_context": "",
        "rag_best_effort_audit": {},
        "rag_best_effort_score": 0.0,
        # ---- CRAG Pipeline ----
        "retrieval_query":        "",
        "context_quality":        "sufficient",  # optimistic default; evaluator overwrites
        "web_supplement_context": "",
        # ---- Dynamic Routing ----
        "rejection_type": None,
        # ---- Observability ----
        "messages": [],
        # ---- Output ----
        "final_filepath":      None,
        "final_markdown_filepath": None,
        "final_pdf_filepath": None,
        "partial_markdown_filepath": None,
        "export_formats":      export_formats or ["PDF", "Word"],
        "final_docx_filepath": None,
        "export_errors":       {},
        # ---- Validation ----
        "validation_failed":     False,
        "validation_reason":     "",
        "validation_suggestion": "",
        # ---- Progress Accumulators (fixed: were missing from previous version) ----
        "used_rag_queries":  [],
        "rag_retrieval_attempts": 0,
        "rag_recovery_attempted": False,
        "section_summaries": section_summaries or [],
        
    }
