"""
Parameter registry for the Advanced Settings system.

Defines every tunable parameter exposed to users and/or admins via the UI.
config.py remains the static fallback; this registry drives the DB layer on top of it.

Each entry carries:
  label          — human-readable name shown in the UI
  description    — short tooltip text (1 sentence)
  group          — grouping key for the UI accordion sections
  type           — "int" | "float" | "str" | "bool"
  default        — value that matches config.py default (used as UI placeholder)
  user_editable  — whether regular users may override this parameter
  admin_only     — if True, only admins can read/write; never returned to users
  sensitive      — if True, value is masked in GET responses ("sk-••••••••")
  min / max      — optional bounds for numeric types (validation)
  choices        — optional list of valid string values (renders as dropdown)
"""

from typing import Any, Dict, Optional

ParameterDef = Dict[str, Any]

LLM_MODEL_CHOICES = [
    "gpt-4o-mini",
    "gpt-4o",
    "gpt-4.1-mini",
    "gpt-4.1",
    "gpt-5.4-mini",
    "gpt-5.4",
    "gpt-5.5",
]

API_COST_PROFILE_CHOICES = [
    "quality_current",
    "balanced_cost",
    "aggressive_cost",
]

RAG_CHUNK_LLM_FILTER_MODE_CHOICES = [
    "auto",
    "always",
    "off",
]

PARAMETER_REGISTRY: Dict[str, ParameterDef] = {

    # =========================================================================
    # GROUP: api_keys — API Keys & External Services (admin only)
    # =========================================================================
    "OPENAI_API_KEY": {
        "label": "OpenAI API Key",
        "description": "Key dùng cho OpenAI models, embeddings và image generation.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "GROQ_API_KEY": {
        "label": "Groq API Key (Legacy Optional)",
        "description": "Key legacy/dự phòng cho tích hợp Groq; pipeline tạo giáo trình mặc định chỉ cần OpenAI.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "GEMINI_API_KEY": {
        "label": "Gemini API Key",
        "description": "Key Gemini dự phòng cho tích hợp AI ngoài OpenAI.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "ANTHROPIC_API_KEY": {
        "label": "Anthropic API Key",
        "description": "Key Anthropic dự phòng cho tích hợp AI ngoài OpenAI.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SERPER_API_KEY": {
        "label": "Serper API Key (Optional)",
        "description": "Key optional cho Google image search nâng cao; mặc định dùng Wikimedia Commons no-key và OpenAI.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "GOOGLE_CLIENT_ID": {
        "label": "Google OAuth Client ID",
        "description": "Client ID dùng cho đăng nhập Google OAuth.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "GOOGLE_CLIENT_SECRET": {
        "label": "Google OAuth Client Secret",
        "description": "Client secret dùng để exchange Google OAuth code.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "GOOGLE_REDIRECT_URI": {
        "label": "Google OAuth Redirect URI",
        "description": "Redirect URI đã cấu hình trong Google Cloud Console.",
        "group": "api_keys",
        "type": "str",
        "default": "http://localhost:8000/api/v1/auth/google/callback",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SMTP_HOST": {
        "label": "SMTP Host",
        "description": "Máy chủ SMTP dùng để gửi email hệ thống.",
        "group": "api_keys",
        "type": "str",
        "default": "smtp.gmail.com",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SMTP_PORT": {
        "label": "SMTP Port",
        "description": "Cổng SMTP dùng để gửi email hệ thống. Dùng 587 cho STARTTLS hoặc 465 cho SSL.",
        "group": "api_keys",
        "type": "int",
        "default": 587,
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SMTP_USER": {
        "label": "SMTP User",
        "description": "Tài khoản SMTP dùng để gửi email.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SMTP_PASSWORD": {
        "label": "SMTP Password",
        "description": "Mật khẩu hoặc app password của SMTP user.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "EMAIL_FROM": {
        "label": "Email From",
        "description": "Địa chỉ người gửi hiển thị trên email hệ thống.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "EMAIL_PROVIDER": {
        "label": "Email Provider",
        "description": "Nhà cung cấp gửi email. Dùng 'smtp' hoặc 'resend'.",
        "group": "api_keys",
        "type": "str",
        "default": "smtp",
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "RESEND_API_KEY": {
        "label": "Resend API Key",
        "description": "API key Resend để gửi email qua HTTPS khi SMTP bị chặn.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SEPAY_API_KEY": {
        "label": "SePay API Key",
        "description": "Key SePay dùng cho tích hợp thanh toán.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SEPAY_ACCOUNT_NUMBER": {
        "label": "SePay Account Number",
        "description": "Số tài khoản SePay hoặc tài khoản nhận thanh toán.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },

    # =========================================================================
    # GROUP: rate_limits — API Rate Limiting (admin only)
    # =========================================================================
    "OPENAI_RATE_LIMIT_ENABLED": {
        "label": "Bật Rate Limit OpenAI",
        "description": "Bật sleep/throttle trước các request OpenAI để tránh 429 khi local và host dùng chung key.",
        "group": "rate_limits",
        "type": "bool",
        "default": True,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_SHARED_RATE_LIMIT_ENABLED": {
        "label": "Dùng Redis Để Chia Sẻ Rate Limit",
        "description": "Khi bật, các worker cùng REDIS_URL sẽ dùng chung bucket rate limit; cần local và host trỏ cùng Redis để phối hợp thật sự.",
        "group": "rate_limits",
        "type": "bool",
        "default": True,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_REQUEST_MIN_INTERVAL_SECONDS": {
        "label": "Khoảng Cách Mặc Định Giữa Request OpenAI",
        "description": "Số giây tối thiểu giữa hai request OpenAI nếu bucket chat/embedding/image không đặt riêng.",
        "group": "rate_limits",
        "type": "float",
        "default": 0.0,
        "min": 0.0,
        "max": 60.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_CHAT_MIN_INTERVAL_SECONDS": {
        "label": "Khoảng Cách Request Chat",
        "description": "Số giây tối thiểu giữa hai request ChatOpenAI/LLM. Gợi ý khi chạy local + host chung key: 1.0-3.0 giây.",
        "group": "rate_limits",
        "type": "float",
        "default": 0.0,
        "min": 0.0,
        "max": 60.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_EMBEDDING_MIN_INTERVAL_SECONDS": {
        "label": "Khoảng Cách Request Embedding",
        "description": "Số giây tối thiểu giữa các batch embedding OpenAI.",
        "group": "rate_limits",
        "type": "float",
        "default": 0.0,
        "min": 0.0,
        "max": 60.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_IMAGE_MIN_INTERVAL_SECONDS": {
        "label": "Khoảng Cách Request Image",
        "description": "Số giây tối thiểu giữa các request tạo ảnh OpenAI.",
        "group": "rate_limits",
        "type": "float",
        "default": 0.0,
        "min": 0.0,
        "max": 120.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_RATE_LIMIT_MAX_RETRIES": {
        "label": "Số Lần Retry Khi Bị 429",
        "description": "Số lần retry với exponential backoff khi OpenAI vẫn trả rate limit.",
        "group": "rate_limits",
        "type": "int",
        "default": 5,
        "min": 0,
        "max": 12,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_RATE_LIMIT_BACKOFF_BASE_SECONDS": {
        "label": "Backoff Cơ Sở Khi Bị 429",
        "description": "Số giây backoff ban đầu khi bị 429; các lần sau tăng theo cấp số nhân.",
        "group": "rate_limits",
        "type": "float",
        "default": 2.0,
        "min": 0.1,
        "max": 60.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_RATE_LIMIT_BACKOFF_MAX_SECONDS": {
        "label": "Backoff Tối Đa Khi Bị 429",
        "description": "Trần số giây chờ giữa các lần retry khi bị rate limit.",
        "group": "rate_limits",
        "type": "float",
        "default": 60.0,
        "min": 1.0,
        "max": 300.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_RATE_LIMIT_JITTER_SECONDS": {
        "label": "Jitter Cho Sleep",
        "description": "Số giây jitter ngẫu nhiên cộng thêm để tránh local và host đánh request cùng một nhịp.",
        "group": "rate_limits",
        "type": "float",
        "default": 0.2,
        "min": 0.0,
        "max": 10.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "WIKIMEDIA_RATE_LIMIT_ENABLED": {
        "label": "Bật Rate Limit Wikimedia",
        "description": "Bật throttle cho Wikimedia Commons search/download để tránh 429 khi nhiều job cùng tải ảnh.",
        "group": "rate_limits",
        "type": "bool",
        "default": True,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "WIKIMEDIA_SHARED_RATE_LIMIT_ENABLED": {
        "label": "Dùng Redis Cho Rate Limit Wikimedia",
        "description": "Khi bật, các worker dùng chung REDIS_URL sẽ chia sẻ cùng bucket Wikimedia.",
        "group": "rate_limits",
        "type": "bool",
        "default": True,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "WIKIMEDIA_REQUEST_MIN_INTERVAL_SECONDS": {
        "label": "Khoảng Cách Mặc Định Wikimedia",
        "description": "Khoảng cách tối thiểu mặc định giữa hai request Wikimedia nếu search/download không đặt riêng.",
        "group": "rate_limits",
        "type": "float",
        "default": 1.0,
        "min": 0.0,
        "max": 30.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "WIKIMEDIA_SEARCH_MIN_INTERVAL_SECONDS": {
        "label": "Khoảng Cách Search Wikimedia",
        "description": "Khoảng cách tối thiểu giữa các request search metadata tới Commons API.",
        "group": "rate_limits",
        "type": "float",
        "default": 1.0,
        "min": 0.0,
        "max": 30.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "WIKIMEDIA_DOWNLOAD_MIN_INTERVAL_SECONDS": {
        "label": "Khoảng Cách Download Wikimedia",
        "description": "Khoảng cách tối thiểu giữa các request tải file ảnh từ Wikimedia/CDN.",
        "group": "rate_limits",
        "type": "float",
        "default": 1.5,
        "min": 0.0,
        "max": 60.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "WIKIMEDIA_RATE_LIMIT_MAX_RETRIES": {
        "label": "Số Lần Retry Wikimedia 429",
        "description": "Số lần retry khi Wikimedia trả 429/Too Many Requests.",
        "group": "rate_limits",
        "type": "int",
        "default": 4,
        "min": 0,
        "max": 10,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "WIKIMEDIA_RATE_LIMIT_BACKOFF_BASE_SECONDS": {
        "label": "Backoff Cơ Sở Wikimedia",
        "description": "Số giây backoff ban đầu khi Wikimedia trả 429.",
        "group": "rate_limits",
        "type": "float",
        "default": 2.0,
        "min": 0.1,
        "max": 60.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "WIKIMEDIA_RATE_LIMIT_BACKOFF_MAX_SECONDS": {
        "label": "Backoff Tối Đa Wikimedia",
        "description": "Trần số giây chờ giữa các lần retry Wikimedia.",
        "group": "rate_limits",
        "type": "float",
        "default": 30.0,
        "min": 1.0,
        "max": 300.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "WIKIMEDIA_RATE_LIMIT_JITTER_SECONDS": {
        "label": "Jitter Wikimedia",
        "description": "Jitter cộng thêm để tránh nhiều worker gọi Wikimedia cùng nhịp.",
        "group": "rate_limits",
        "type": "float",
        "default": 0.5,
        "min": 0.0,
        "max": 10.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },

    # =========================================================================
    # GROUP: rag — RAG & Tìm Kiếm
    # =========================================================================
    "RAG_INITIAL_K": {
        "label": "K Lấy Kết Quả Ban Đầu",
        "description": "Số chunk được lấy trong lần RAG đầu tiên trước khi làm giàu thêm ngữ cảnh.",
        "group": "rag",
        "type": "int",
        "default": 8,
        "min": 1,
        "max": 20,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_TOOL_K": {
        "label": "K Lấy Kết Quả Theo Tool",
        "description": "Số chunk được lấy mỗi vòng tool-call trong quá trình làm giàu nội dung của writer.",
        "group": "rag",
        "type": "int",
        "default": 8,
        "min": 1,
        "max": 20,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_TOP_K": {
        "label": "K Lấy Kết Quả Tổng Hợp",
        "description": "Số chunk mục tiêu cho các truy vấn RAG tổng hợp.",
        "group": "rag",
        "type": "int",
        "default": 8,
        "min": 1,
        "max": 20,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_TOOL_MAX_ROUNDS": {
        "label": "Số Vòng Tool RAG Tối Đa",
        "description": "Số vòng truy vấn bổ sung tối đa khi agent cần làm giàu ngữ cảnh.",
        "group": "rag",
        "type": "int",
        "default": 4,
        "min": 1,
        "max": 8,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAG_CONTEXT_QUALITY_MIN_CHARS": {
        "label": "Ngưỡng Chất Lượng Ngữ Cảnh (ký tự)",
        "description": "Tổng số ký tự RAG tối thiểu cần đạt trước khi bắt đầu viết; dưới ngưỡng này sẽ thử lại.",
        "group": "rag",
        "type": "int",
        "default": 3500,
        "min": 500,
        "max": 10000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAG_TARGETED_RECOVERY_ENABLED": {
        "label": "Bật Recovery RAG Theo Mục",
        "description": "Khi thiếu ngữ cảnh, crawl bổ sung một số nguồn cho subsection hiện tại trước khi tiếp tục.",
        "group": "rag",
        "type": "bool",
        "default": True,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAG_TARGETED_RECOVERY_RESULTS_PER_QUERY": {
        "label": "Kết Quả Recovery Mỗi Query",
        "description": "Số kết quả tìm kiếm lấy cho một query recovery RAG.",
        "group": "rag",
        "type": "int",
        "default": 6,
        "min": 1,
        "max": 20,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAG_TARGETED_RECOVERY_MAX_ROOT_URLS": {
        "label": "URL Recovery Tối Đa",
        "description": "Số URL sạch tối đa được crawl trong một vòng recovery RAG.",
        "group": "rag",
        "type": "int",
        "default": 5,
        "min": 1,
        "max": 20,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAG_MAX_CONTEXT_RETRIES": {
        "label": "Số Lần Thử Lại Ngữ Cảnh Tối Đa",
        "description": "Số lần tối đa query reformulator thử lại trước khi writer tiếp tục với ngữ cảnh hiện có.",
        "group": "rag",
        "type": "int",
        "default": 4,
        "min": 0,
        "max": 5,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAG_BEST_EFFORT_AFTER_RETRIES": {
        "label": "Dùng Ngữ Cảnh Tốt Nhất Sau Khi Hết Retry",
        "description": "Khi bật, nếu vẫn thiếu ngữ cảnh sau số lần thử lại tối đa, hệ thống dùng context tốt nhất tìm được thay vì dừng toàn bộ workflow.",
        "group": "rag",
        "type": "bool",
        "default": True,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "MIN_RELEVANCE_SCORE": {
        "label": "Điểm Liên Quan Tối Thiểu",
        "description": "Ngưỡng lọc ChromaDB sau khi tìm kiếm; các chunk dưới điểm này bị loại bỏ.",
        "group": "rag",
        "type": "float",
        "default": 0.22,
        "min": 0.0,
        "max": 1.0,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_TRUSTED_DOMAIN_QUOTA": {
        "label": "Hạn Mức Domain Tin Cậy",
        "description": "Số chunk tối đa được lấy từ một domain tin cậy như Wikipedia hay arXiv.",
        "group": "rag",
        "type": "int",
        "default": 4,
        "min": 1,
        "max": 20,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_DEFAULT_DOMAIN_QUOTA": {
        "label": "Hạn Mức Domain Thông Thường",
        "description": "Số chunk tối đa từ một domain không tin cậy; tránh thiên lệch từ một nguồn duy nhất.",
        "group": "rag",
        "type": "int",
        "default": 2,
        "min": 1,
        "max": 10,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_SEMANTIC_DEDUP_THRESHOLD": {
        "label": "Ngưỡng Khử Trùng Ngữ Nghĩa",
        "description": "Ngưỡng cosine similarity để khử trùng; giá trị thấp hơn loại nhiều chunk hơn.",
        "group": "rag",
        "type": "float",
        "default": 0.85,
        "min": 0.5,
        "max": 1.0,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_CHUNK_LLM_FILTER_MODE": {
        "label": "Chế Độ Lọc Chunk Bằng LLM",
        "description": "Kiểm soát binary classifier trong Retriever: auto chỉ kiểm tra chunk nghi ngờ ở balanced_cost, always giữ hành vi cũ, off tắt LLM filter.",
        "group": "rag",
        "type": "str",
        "default": "auto",
        "choices": RAG_CHUNK_LLM_FILTER_MODE_CHOICES,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },

    # =========================================================================
    # GROUP: generation — Tạo Nội Dung
    # =========================================================================
    "LLM_MODEL_CHEAP": {
        "label": "Model Phụ Trợ",
        "description": "Model LLM dùng cho reviewer, illustrator và các agent phụ trợ; có thể chọn model cao hơn nếu chấp nhận tăng chi phí và độ trễ.",
        "group": "generation",
        "type": "str",
        "default": "gpt-4o-mini",
        "choices": LLM_MODEL_CHOICES,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "LLM_MODEL_PREMIUM": {
        "label": "Model Chính",
        "description": "Model LLM dùng cho planner và content writer; mặc định ổn định là gpt-4.1, Admin có thể nâng lên model cao hơn khi cần chất lượng mạnh hơn.",
        "group": "generation",
        "type": "str",
        "default": "gpt-4.1",
        "choices": LLM_MODEL_CHOICES,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "API_COST_PROFILE": {
        "label": "Hồ Sơ Chi Phí API",
        "description": "Chọn mức tối ưu chi phí có thể rollback: giữ nguyên chất lượng hiện tại, cân bằng chi phí, hoặc chế độ mạnh sau benchmark.",
        "group": "generation",
        "type": "str",
        "default": "balanced_cost",
        "choices": API_COST_PROFILE_CHOICES,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "REVIEWER_MAX_REVISIONS": {
        "label": "Số Lần Chỉnh Sửa Tối Đa",
        "description": "Số vòng reviewer→writer tối đa mỗi mục trước khi buộc chấp nhận; 0 tắt hoàn toàn bước kiểm duyệt.",
        "group": "generation",
        "type": "int",
        "default": 2,
        "min": 0,
        "max": 5,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "WRITER_RETRIEVAL_MAX_ROUNDS": {
        "label": "Số Vòng Lấy Dữ Liệu của Writer",
        "description": "Số vòng tool-call tối đa ContextEvaluator có thể dùng để bổ sung ngữ cảnh trước khi viết.",
        "group": "generation",
        "type": "int",
        "default": 3,
        "min": 0,
        "max": 8,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "WRITER_MAX_PRIOR_SUMMARIES": {
        "label": "Số Tóm Tắt Trước Đưa Vào Prompt",
        "description": "Số tóm tắt mục trước tối đa được đưa vào prompt của writer; tăng cao có thể vượt ngân sách token.",
        "group": "generation",
        "type": "int",
        "default": 6,
        "min": 0,
        "max": 15,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CONTENT_LEVEL_SHORT_MIN_WORDS": {
        "label": "Số Từ Tối Thiểu - Ngắn",
        "description": "Số từ tối thiểu mỗi mục khi chọn chế độ Ngắn; backend quy đổi sang ngưỡng ký tự cho Writer/Reviewer.",
        "group": "generation",
        "type": "int",
        "default": 300,
        "min": 100,
        "max": 2000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CONTENT_LEVEL_SHORT_MAX_WORDS": {
        "label": "Số Từ Tối Đa - Ngắn",
        "description": "Số từ tối đa mục tiêu mỗi mục khi chọn chế độ Ngắn; Reviewer sẽ yêu cầu cô đọng nếu vượt quá nhiều.",
        "group": "generation",
        "type": "int",
        "default": 500,
        "min": 100,
        "max": 3000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CONTENT_LEVEL_MEDIUM_MIN_WORDS": {
        "label": "Số Từ Tối Thiểu - Trung Bình",
        "description": "Số từ tối thiểu mỗi mục khi chọn chế độ Trung Bình.",
        "group": "generation",
        "type": "int",
        "default": 500,
        "min": 100,
        "max": 2500,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CONTENT_LEVEL_MEDIUM_MAX_WORDS": {
        "label": "Số Từ Tối Đa - Trung Bình",
        "description": "Số từ tối đa mục tiêu mỗi mục khi chọn chế độ Trung Bình.",
        "group": "generation",
        "type": "int",
        "default": 800,
        "min": 100,
        "max": 4000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CONTENT_LEVEL_LONG_MIN_WORDS": {
        "label": "Số Từ Tối Thiểu - Dài",
        "description": "Số từ tối thiểu mỗi mục khi chọn chế độ Dài.",
        "group": "generation",
        "type": "int",
        "default": 800,
        "min": 100,
        "max": 4000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CONTENT_LEVEL_LONG_MAX_WORDS": {
        "label": "Số Từ Tối Đa - Dài",
        "description": "Số từ tối đa mục tiêu mỗi mục khi chọn chế độ Dài.",
        "group": "generation",
        "type": "int",
        "default": 1200,
        "min": 100,
        "max": 6000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CONTENT_LEVEL_VERY_LONG_MIN_WORDS": {
        "label": "Số Từ Tối Thiểu - Rất Dài",
        "description": "Số từ tối thiểu mỗi mục khi chọn chế độ Rất Dài.",
        "group": "generation",
        "type": "int",
        "default": 1200,
        "min": 100,
        "max": 6000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CONTENT_LEVEL_VERY_LONG_MAX_WORDS": {
        "label": "Số Từ Tối Đa - Rất Dài",
        "description": "Số từ tối đa mục tiêu mỗi mục khi chọn chế độ Rất Dài.",
        "group": "generation",
        "type": "int",
        "default": 1500,
        "min": 100,
        "max": 8000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CONTENT_WORD_TO_CHAR_RATIO_VI": {
        "label": "Ký Tự Mỗi Từ - Tiếng Việt",
        "description": "Hệ số quy đổi số từ sang ký tự cho giáo trình tiếng Việt; dùng để tính dải min/max ký tự.",
        "group": "generation",
        "type": "float",
        "default": 5.0,
        "min": 3.0,
        "max": 10.0,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CONTENT_WORD_TO_CHAR_RATIO_EN": {
        "label": "Ký Tự Mỗi Từ - Tiếng Anh",
        "description": "Hệ số quy đổi số từ sang ký tự cho giáo trình tiếng Anh; thường cao hơn tiếng Việt.",
        "group": "generation",
        "type": "float",
        "default": 6.0,
        "min": 3.0,
        "max": 10.0,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },

    # =========================================================================
    # GROUP: ingestion — Thu Thập & Phân Đoạn
    # =========================================================================
    "CHUNK_SIZE": {
        "label": "Kích Thước Chunk (ký tự)",
        "description": "Độ dài mỗi chunk văn bản trước khi embedding; thay đổi ảnh hưởng đến toàn bộ chất lượng RAG.",
        "group": "ingestion",
        "type": "int",
        "default": 2000,
        "min": 300,
        "max": 5000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CHUNK_OVERLAP": {
        "label": "Độ Chồng Lấp Chunk (ký tự)",
        "description": "Số ký tự chồng lấp giữa các chunk liên tiếp để bảo toàn ngữ cảnh tại vùng biên.",
        "group": "ingestion",
        "type": "int",
        "default": 300,
        "min": 0,
        "max": 2000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "SEARCH_RESULTS_PER_QUERY": {
        "label": "Kết Quả Tìm Kiếm Mỗi Query",
        "description": "Số URL được lấy từ search engine cho mỗi query trong quá trình thu thập dữ liệu.",
        "group": "ingestion",
        "type": "int",
        "default": 20,
        "min": 5,
        "max": 100,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "SEARCH_QUERIES_PER_LANGUAGE": {
        "label": "Query Mỗi Ngôn Ngữ",
        "description": "Số query nền lấy từ bộ mở rộng truy vấn cho mỗi ngôn ngữ; giảm để smoke test nhanh hơn.",
        "group": "ingestion",
        "type": "int",
        "default": 6,
        "min": 1,
        "max": 6,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "SEARCH_MAX_WORKERS": {
        "label": "Số Luồng Tìm Kiếm",
        "description": "Số truy vấn tìm kiếm web chạy song song; tăng cao có thể nhanh hơn nhưng dễ gặp giới hạn dịch vụ.",
        "group": "ingestion",
        "type": "int",
        "default": 4,
        "min": 1,
        "max": 12,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "TARGETED_CRAWL_QUERIES_PER_CHAPTER": {
        "label": "Query Theo Chương",
        "description": "Số query bổ sung lấy từ từng chương sau khi duyệt đề cương.",
        "group": "ingestion",
        "type": "int",
        "default": 2,
        "min": 0,
        "max": 10,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "TARGETED_CRAWL_MAX_QUERIES": {
        "label": "Tổng Query Theo Đề Cương",
        "description": "Giới hạn tổng số query bổ sung lấy từ đề cương đã xác nhận.",
        "group": "ingestion",
        "type": "int",
        "default": 16,
        "min": 0,
        "max": 50,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "URL_FILTER_MAX_WORKERS": {
        "label": "Số Luồng Lọc URL",
        "description": "Số URL được kiểm tra content-type song song trước khi crawl.",
        "group": "ingestion",
        "type": "int",
        "default": 6,
        "min": 1,
        "max": 12,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAWL_MAX_WORKERS": {
        "label": "Số Luồng Crawl",
        "description": "Số trang nguồn được crawl song song; tăng cao có thể nhanh hơn nhưng tạo nhiều request mạng hơn.",
        "group": "ingestion",
        "type": "int",
        "default": 5,
        "min": 1,
        "max": 12,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAWL_MAX_SUB_LINKS": {
        "label": "Link Con Mỗi Trang",
        "description": "Số link nội bộ tối đa được crawl thêm từ mỗi trang nguồn.",
        "group": "ingestion",
        "type": "int",
        "default": 3,
        "min": 0,
        "max": 20,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAWL_MAX_ROOT_URLS": {
        "label": "Giới Hạn URL Gốc",
        "description": "Số URL hợp lệ tối đa được đưa vào deep crawl; đặt 0 để không giới hạn.",
        "group": "ingestion",
        "type": "int",
        "default": 80,
        "min": 0,
        "max": 200,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAWL_MAX_DEPTH2_LINKS": {
        "label": "Link Tầng 2 Mỗi Trang",
        "description": "Số link tầng 2 tối đa khi trang nguồn là trang điều hướng; đặt 0 để tắt crawl sâu tầng 2.",
        "group": "ingestion",
        "type": "int",
        "default": 1,
        "min": 0,
        "max": 10,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "MAX_CHUNKS_TO_EMBED": {
        "label": "Số Chunk Tối Đa Để Embedding",
        "description": "Giới hạn tổng số chunk được xử lý mỗi lần thu thập; bộ lọc heuristic sẽ giảm số này trước khi embedding.",
        "group": "ingestion",
        "type": "int",
        "default": 1200,
        "min": 100,
        "max": 5000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "MIN_EMBEDDED_UNIQUE_SOURCES": {
        "label": "Số Nguồn Tối Thiểu Sau Embedding",
        "description": "Ngưỡng cảnh báo nếu corpus cuối cùng có quá ít URL nguồn riêng biệt.",
        "group": "source_diversity",
        "type": "int",
        "default": 12,
        "min": 1,
        "max": 100,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "MIN_EMBEDDED_UNIQUE_DOMAINS": {
        "label": "Số Domain Tối Thiểu Sau Embedding",
        "description": "Ngưỡng cảnh báo nếu corpus cuối cùng có quá ít domain riêng biệt.",
        "group": "source_diversity",
        "type": "int",
        "default": 8,
        "min": 1,
        "max": 100,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "TARGET_EMBEDDED_UNIQUE_SOURCES": {
        "label": "Số Nguồn Mục Tiêu",
        "description": "Mục tiêu diversity khi hệ thống thu thập nguồn học thuật cho một giáo trình.",
        "group": "source_diversity",
        "type": "int",
        "default": 15,
        "min": 1,
        "max": 150,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "MAX_CHUNKS_PER_SOURCE_DEFAULT": {
        "label": "Chunk Tối Đa Mỗi Nguồn Thường",
        "description": "Giới hạn chunk từ một URL nguồn thông thường sau lọc relevance.",
        "group": "source_diversity",
        "type": "int",
        "default": 180,
        "min": 10,
        "max": 2000,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "MAX_CHUNKS_PER_PRIORITY_PDF": {
        "label": "Chunk Tối Đa Mỗi PDF Giáo Trình",
        "description": "Giới hạn chunk từ một priority textbook PDF sau lọc relevance.",
        "group": "source_diversity",
        "type": "int",
        "default": 300,
        "min": 10,
        "max": 3000,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "MAX_SINGLE_SOURCE_CHUNK_RATIO": {
        "label": "Tỷ Lệ Chunk Tối Đa Từ Một Nguồn",
        "description": "Trần tỷ lệ chunk từ một URL nguồn, không áp dụng cho direct custom URL.",
        "group": "source_diversity",
        "type": "float",
        "default": 0.30,
        "min": 0.05,
        "max": 1.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "CUSTOM_URL_DIRECT_SOURCE_CAP": {
        "label": "Chunk Tối Đa Cho URL Tự Nhập",
        "description": "Giới hạn chunk cao hơn cho nguồn URL trực tiếp do người dùng chọn.",
        "group": "source_diversity",
        "type": "int",
        "default": 500,
        "min": 10,
        "max": 5000,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "MIN_CITABLE_SOURCES": {
        "label": "Số Nguồn Trích Dẫn Tối Thiểu",
        "description": "Mục tiêu nguồn có thể trích dẫn khi tạo danh mục tài liệu tham khảo.",
        "group": "source_diversity",
        "type": "int",
        "default": 10,
        "min": 1,
        "max": 100,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "EMBEDDING_BATCH_SIZE": {
        "label": "Kích Thước Batch Embedding",
        "description": "Số chunk gửi trong mỗi batch embedding; batch lớn thường nhanh hơn nhưng dùng nhiều tài nguyên hơn.",
        "group": "ingestion",
        "type": "int",
        "default": 200,
        "min": 20,
        "max": 1000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CHROMADB_BATCH_SIZE": {
        "label": "Kích Thước Batch ChromaDB",
        "description": "Số chunk được ghi vào ChromaDB trong mỗi batch.",
        "group": "ingestion",
        "type": "int",
        "default": 100,
        "min": 10,
        "max": 1000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "MIN_SNIPPET_SCORE": {
        "label": "Điểm Snippet Tối Thiểu",
        "description": "Ngưỡng chất lượng snippet URL khi thu thập dữ liệu; URL dưới ngưỡng này bị bỏ qua.",
        "group": "ingestion",
        "type": "float",
        "default": 0.3,
        "min": 0.0,
        "max": 1.0,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },

    # =========================================================================
    # GROUP: domain_caps — Giới Hạn Domain (chỉ admin)
    # =========================================================================
    "MAX_CHUNKS_PER_DOMAIN": {
        "label": "Giới Hạn Domain Cơ Bản",
        "description": "Số chunk tối đa mỗi domain khi không có giới hạn theo ngôn ngữ nào được áp dụng.",
        "group": "domain_caps",
        "type": "int",
        "default": 35,
        "min": 1,
        "max": 200,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "VI_DOMAIN_CAP": {
        "label": "Giới Hạn Domain Tiếng Việt",
        "description": "Số chunk tối đa mỗi domain cho nội dung tiếng Việt; cao hơn tiếng Anh vì nguồn tiếng Việt khan hiếm hơn.",
        "group": "domain_caps",
        "type": "int",
        "default": 80,
        "min": 10,
        "max": 500,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "EN_DOMAIN_CAP": {
        "label": "Giới Hạn Domain Tiếng Anh",
        "description": "Số chunk tối đa mỗi domain cho nội dung tiếng Anh; source-level caps sẽ chống lệch theo từng tài liệu.",
        "group": "domain_caps",
        "type": "int",
        "default": 80,
        "min": 5,
        "max": 300,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
}

# -------------------------------------------------------------------------
# Group metadata — labels and ordering for UI accordions
# -------------------------------------------------------------------------
PARAMETER_GROUPS: Dict[str, Dict[str, str]] = {
    "api_keys": {
        "label": "API Keys",
        "description": "Khóa truy cập và secret cho các dịch vụ ngoài; chỉ quản trị viên được chỉnh.",
    },
    "rate_limits": {
        "label": "API Rate Limit",
        "description": "Điều tiết request OpenAI khi local và host dùng chung API key.",
    },
    "rag": {
        "label": "RAG & Tìm Kiếm",
        "description": "Kiểm soát cách tài liệu được tìm kiếm và lọc từ cơ sở tri thức.",
    },
    "generation": {
        "label": "Tạo Nội Dung",
        "description": "Kiểm soát model LLM, số vòng chỉnh sửa và hành vi của writer.",
    },
    "ingestion": {
        "label": "Thu Thập & Phân Đoạn",
        "description": "Kiểm soát cách nội dung web được thu thập, phân đoạn và lập chỉ mục.",
    },
    "domain_caps": {
        "label": "Giới Hạn Domain",
        "description": "Giới hạn số chunk tối đa từ một domain duy nhất theo từng ngôn ngữ.",
    },
    "source_diversity": {
        "label": "Đa Dạng Nguồn",
        "description": "Kiểm soát số chunk và mức cân bằng giữa các URL nguồn sau khi crawl.",
    },
}


def get_user_registry() -> Dict[str, ParameterDef]:
    """Return only parameters that users are allowed to edit."""
    return {k: v for k, v in PARAMETER_REGISTRY.items() if v["user_editable"]}


def get_admin_registry() -> Dict[str, ParameterDef]:
    """Return all parameters (users + admin-only) for the admin panel."""
    return PARAMETER_REGISTRY


def get_defaults() -> Dict[str, Any]:
    """Return a flat dict of {param_key: default_value} for all parameters."""
    return {k: v["default"] for k, v in PARAMETER_REGISTRY.items()}
