"""
Parameter registry for the Advanced Settings system.

Defines every tunable parameter exposed to users and/or admins via the UI.
config.py remains the static fallback; this registry drives the DB layer on top of it.

Each entry carries:
  label          — human-readable name shown in the UI
  description    — short tooltip text (1 sentence)
  group          — grouping key for the UI accordion sections
  type           — "int" | "float" | "str" | "bool"
  default        — value that matches config.py default (used as UI placeholder)
  user_editable  — whether regular users may override this parameter
  admin_only     — if True, only admins can read/write; never returned to users
  sensitive      — if True, value is masked in GET responses ("sk-••••••••")
  min / max      — optional bounds for numeric types (validation)
  choices        — optional list of valid string values (renders as dropdown)
"""

from typing import Any, Dict, Optional

ParameterDef = Dict[str, Any]

LLM_MODEL_CHOICES = [
    "gpt-4o-mini",
    "gpt-4o",
    "gpt-4.1-mini",
    "gpt-4.1",
    "gpt-5.4-mini",
    "gpt-5.4",
    "gpt-5.5",
]

PARAMETER_REGISTRY: Dict[str, ParameterDef] = {

    # =========================================================================
    # GROUP: api_keys — API Keys & External Services (admin only)
    # =========================================================================
    "OPENAI_API_KEY": {
        "label": "OpenAI API Key",
        "description": "Key dùng cho OpenAI models, embeddings và image generation.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "GROQ_API_KEY": {
        "label": "Groq API Key",
        "description": "Key dùng cho ValidatorAgent qua Groq.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "GEMINI_API_KEY": {
        "label": "Gemini API Key",
        "description": "Key Gemini dự phòng cho tích hợp AI ngoài OpenAI.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "ANTHROPIC_API_KEY": {
        "label": "Anthropic API Key",
        "description": "Key Anthropic dự phòng cho tích hợp AI ngoài OpenAI.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SERPER_API_KEY": {
        "label": "Serper API Key",
        "description": "Key dùng cho Google image search trong IllustratorAgent.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "GOOGLE_CLIENT_ID": {
        "label": "Google OAuth Client ID",
        "description": "Client ID dùng cho đăng nhập Google OAuth.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "GOOGLE_CLIENT_SECRET": {
        "label": "Google OAuth Client Secret",
        "description": "Client secret dùng để exchange Google OAuth code.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "GOOGLE_REDIRECT_URI": {
        "label": "Google OAuth Redirect URI",
        "description": "Redirect URI đã cấu hình trong Google Cloud Console.",
        "group": "api_keys",
        "type": "str",
        "default": "http://localhost:8000/api/v1/auth/google/callback",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SMTP_HOST": {
        "label": "SMTP Host",
        "description": "Máy chủ SMTP dùng để gửi email hệ thống.",
        "group": "api_keys",
        "type": "str",
        "default": "smtp.gmail.com",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SMTP_PORT": {
        "label": "SMTP Port",
        "description": "Cổng SMTP dùng để gửi email hệ thống. Dùng 587 cho STARTTLS hoặc 465 cho SSL.",
        "group": "api_keys",
        "type": "str",
        "default": "587",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SMTP_USER": {
        "label": "SMTP User",
        "description": "Tài khoản SMTP dùng để gửi email.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SMTP_PASSWORD": {
        "label": "SMTP Password",
        "description": "Mật khẩu hoặc app password của SMTP user.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "EMAIL_FROM": {
        "label": "Email From",
        "description": "Địa chỉ người gửi hiển thị trên email hệ thống.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "EMAIL_PROVIDER": {
        "label": "Email Provider",
        "description": "Nhà cung cấp gửi email. Dùng 'smtp' hoặc 'resend'.",
        "group": "api_keys",
        "type": "str",
        "default": "smtp",
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "RESEND_API_KEY": {
        "label": "Resend API Key",
        "description": "API key Resend để gửi email qua HTTPS khi SMTP bị chặn.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SEPAY_API_KEY": {
        "label": "SePay API Key",
        "description": "Key SePay dùng cho tích hợp thanh toán.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },
    "SEPAY_ACCOUNT_NUMBER": {
        "label": "SePay Account Number",
        "description": "Số tài khoản SePay hoặc tài khoản nhận thanh toán.",
        "group": "api_keys",
        "type": "str",
        "default": "",
        "user_editable": False,
        "admin_only": True,
        "sensitive": True,
    },

    # =========================================================================
    # GROUP: rate_limits — API Rate Limiting (admin only)
    # =========================================================================
    "OPENAI_RATE_LIMIT_ENABLED": {
        "label": "Bật Rate Limit OpenAI",
        "description": "Bật sleep/throttle trước các request OpenAI để tránh 429 khi local và host dùng chung key.",
        "group": "rate_limits",
        "type": "bool",
        "default": False,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_SHARED_RATE_LIMIT_ENABLED": {
        "label": "Dùng Redis Để Chia Sẻ Rate Limit",
        "description": "Khi bật, các worker cùng REDIS_URL sẽ dùng chung bucket rate limit; cần local và host trỏ cùng Redis để phối hợp thật sự.",
        "group": "rate_limits",
        "type": "bool",
        "default": True,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_REQUEST_MIN_INTERVAL_SECONDS": {
        "label": "Khoảng Cách Mặc Định Giữa Request OpenAI",
        "description": "Số giây tối thiểu giữa hai request OpenAI nếu bucket chat/embedding/image không đặt riêng.",
        "group": "rate_limits",
        "type": "float",
        "default": 0.0,
        "min": 0.0,
        "max": 60.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_CHAT_MIN_INTERVAL_SECONDS": {
        "label": "Khoảng Cách Request Chat",
        "description": "Số giây tối thiểu giữa hai request ChatOpenAI/LLM. Gợi ý khi chạy local + host chung key: 1.0-3.0 giây.",
        "group": "rate_limits",
        "type": "float",
        "default": 0.0,
        "min": 0.0,
        "max": 60.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_EMBEDDING_MIN_INTERVAL_SECONDS": {
        "label": "Khoảng Cách Request Embedding",
        "description": "Số giây tối thiểu giữa các batch embedding OpenAI.",
        "group": "rate_limits",
        "type": "float",
        "default": 0.0,
        "min": 0.0,
        "max": 60.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_IMAGE_MIN_INTERVAL_SECONDS": {
        "label": "Khoảng Cách Request Image",
        "description": "Số giây tối thiểu giữa các request tạo ảnh OpenAI.",
        "group": "rate_limits",
        "type": "float",
        "default": 0.0,
        "min": 0.0,
        "max": 120.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_RATE_LIMIT_MAX_RETRIES": {
        "label": "Số Lần Retry Khi Bị 429",
        "description": "Số lần retry với exponential backoff khi OpenAI vẫn trả rate limit.",
        "group": "rate_limits",
        "type": "int",
        "default": 5,
        "min": 0,
        "max": 12,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_RATE_LIMIT_BACKOFF_BASE_SECONDS": {
        "label": "Backoff Cơ Sở Khi Bị 429",
        "description": "Số giây backoff ban đầu khi bị 429; các lần sau tăng theo cấp số nhân.",
        "group": "rate_limits",
        "type": "float",
        "default": 2.0,
        "min": 0.1,
        "max": 60.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_RATE_LIMIT_BACKOFF_MAX_SECONDS": {
        "label": "Backoff Tối Đa Khi Bị 429",
        "description": "Trần số giây chờ giữa các lần retry khi bị rate limit.",
        "group": "rate_limits",
        "type": "float",
        "default": 60.0,
        "min": 1.0,
        "max": 300.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "OPENAI_RATE_LIMIT_JITTER_SECONDS": {
        "label": "Jitter Cho Sleep",
        "description": "Số giây jitter ngẫu nhiên cộng thêm để tránh local và host đánh request cùng một nhịp.",
        "group": "rate_limits",
        "type": "float",
        "default": 0.2,
        "min": 0.0,
        "max": 10.0,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },

    # =========================================================================
    # GROUP: rag — RAG & Tìm Kiếm
    # =========================================================================
    "RAG_INITIAL_K": {
        "label": "K Lấy Kết Quả Ban Đầu",
        "description": "Số chunk được lấy trong lần RAG đầu tiên trước khi làm giàu thêm ngữ cảnh.",
        "group": "rag",
        "type": "int",
        "default": 5,
        "min": 1,
        "max": 20,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_TOOL_K": {
        "label": "K Lấy Kết Quả Theo Tool",
        "description": "Số chunk được lấy mỗi vòng tool-call trong quá trình làm giàu nội dung của writer.",
        "group": "rag",
        "type": "int",
        "default": 5,
        "min": 1,
        "max": 20,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_TOOL_MAX_ROUNDS": {
        "label": "Số Vòng Làm Giàu Tối Đa",
        "description": "Số vòng tool-call tối đa writer có thể dùng để bổ sung ngữ cảnh; tăng cao làm chậm tốc độ tạo.",
        "group": "rag",
        "type": "int",
        "default": 4,
        "min": 0,
        "max": 10,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAG_CONTEXT_QUALITY_MIN_CHARS": {
        "label": "Ngưỡng Chất Lượng Ngữ Cảnh (ký tự)",
        "description": "Tổng số ký tự RAG tối thiểu cần đạt trước khi bắt đầu viết; dưới ngưỡng này sẽ thử lại.",
        "group": "rag",
        "type": "int",
        "default": 3000,
        "min": 500,
        "max": 10000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAG_MAX_CONTEXT_RETRIES": {
        "label": "Số Lần Thử Lại Ngữ Cảnh Tối Đa",
        "description": "Số lần tối đa query reformulator thử lại trước khi writer tiếp tục với ngữ cảnh hiện có.",
        "group": "rag",
        "type": "int",
        "default": 2,
        "min": 0,
        "max": 5,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAG_BEST_EFFORT_AFTER_RETRIES": {
        "label": "Dùng Ngữ Cảnh Tốt Nhất Sau Khi Hết Retry",
        "description": "Khi bật, nếu vẫn thiếu ngữ cảnh sau số lần thử lại tối đa, hệ thống dùng context tốt nhất tìm được thay vì dừng toàn bộ workflow.",
        "group": "rag",
        "type": "bool",
        "default": False,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "MIN_RELEVANCE_SCORE": {
        "label": "Điểm Liên Quan Tối Thiểu",
        "description": "Ngưỡng lọc ChromaDB sau khi tìm kiếm; các chunk dưới điểm này bị loại bỏ.",
        "group": "rag",
        "type": "float",
        "default": 0.22,
        "min": 0.0,
        "max": 1.0,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_TRUSTED_DOMAIN_QUOTA": {
        "label": "Hạn Mức Domain Tin Cậy",
        "description": "Số chunk tối đa được lấy từ một domain tin cậy như Wikipedia hay arXiv.",
        "group": "rag",
        "type": "int",
        "default": 3,
        "min": 1,
        "max": 20,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_DEFAULT_DOMAIN_QUOTA": {
        "label": "Hạn Mức Domain Thông Thường",
        "description": "Số chunk tối đa từ một domain không tin cậy; tránh thiên lệch từ một nguồn duy nhất.",
        "group": "rag",
        "type": "int",
        "default": 1,
        "min": 1,
        "max": 10,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "RAG_SEMANTIC_DEDUP_THRESHOLD": {
        "label": "Ngưỡng Khử Trùng Ngữ Nghĩa",
        "description": "Ngưỡng cosine similarity để khử trùng; giá trị thấp hơn loại nhiều chunk hơn.",
        "group": "rag",
        "type": "float",
        "default": 0.85,
        "min": 0.5,
        "max": 1.0,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },

    # =========================================================================
    # GROUP: generation — Tạo Nội Dung
    # =========================================================================
    "LLM_MODEL_CHEAP": {
        "label": "Model Phụ Trợ",
        "description": "Model LLM dùng cho reviewer, illustrator và các agent phụ trợ; có thể chọn model cao hơn nếu chấp nhận tăng chi phí và độ trễ.",
        "group": "generation",
        "type": "str",
        "default": "gpt-4o-mini",
        "choices": LLM_MODEL_CHOICES,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "LLM_MODEL_PREMIUM": {
        "label": "Model Chính",
        "description": "Model LLM dùng cho planner và content writer; mặc định ổn định là gpt-4.1, Admin có thể nâng lên model cao hơn khi cần chất lượng mạnh hơn.",
        "group": "generation",
        "type": "str",
        "default": "gpt-4.1",
        "choices": LLM_MODEL_CHOICES,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "REVIEWER_MAX_REVISIONS": {
        "label": "Số Lần Chỉnh Sửa Tối Đa",
        "description": "Số vòng reviewer→writer tối đa mỗi mục trước khi buộc chấp nhận; 0 tắt hoàn toàn bước kiểm duyệt.",
        "group": "generation",
        "type": "int",
        "default": 2,
        "min": 0,
        "max": 5,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "WRITER_RETRIEVAL_MAX_ROUNDS": {
        "label": "Số Vòng Lấy Dữ Liệu của Writer",
        "description": "Số vòng tool-call tối đa ContextRetrievalAgent có thể dùng để bổ sung ngữ cảnh khi viết.",
        "group": "generation",
        "type": "int",
        "default": 3,
        "min": 0,
        "max": 8,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "WRITER_MAX_PRIOR_SUMMARIES": {
        "label": "Số Tóm Tắt Trước Đưa Vào Prompt",
        "description": "Số tóm tắt mục trước tối đa được đưa vào prompt của writer; tăng cao có thể vượt ngân sách token.",
        "group": "generation",
        "type": "int",
        "default": 6,
        "min": 0,
        "max": 15,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },

    # =========================================================================
    # GROUP: ingestion — Thu Thập & Phân Đoạn
    # =========================================================================
    "CHUNK_SIZE": {
        "label": "Kích Thước Chunk (ký tự)",
        "description": "Độ dài mỗi chunk văn bản trước khi embedding; thay đổi ảnh hưởng đến toàn bộ chất lượng RAG.",
        "group": "ingestion",
        "type": "int",
        "default": 1500,
        "min": 300,
        "max": 5000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CHUNK_OVERLAP": {
        "label": "Độ Chồng Lấp Chunk (ký tự)",
        "description": "Số ký tự chồng lấp giữa các chunk liên tiếp để bảo toàn ngữ cảnh tại vùng biên.",
        "group": "ingestion",
        "type": "int",
        "default": 300,
        "min": 0,
        "max": 2000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "SEARCH_RESULTS_PER_QUERY": {
        "label": "Kết Quả Tìm Kiếm Mỗi Query",
        "description": "Số URL được lấy từ search engine cho mỗi query trong quá trình thu thập dữ liệu.",
        "group": "ingestion",
        "type": "int",
        "default": 30,
        "min": 5,
        "max": 100,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "SEARCH_QUERIES_PER_LANGUAGE": {
        "label": "Query Mỗi Ngôn Ngữ",
        "description": "Số query nền lấy từ bộ mở rộng truy vấn cho mỗi ngôn ngữ; giảm để smoke test nhanh hơn.",
        "group": "ingestion",
        "type": "int",
        "default": 6,
        "min": 1,
        "max": 6,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "SEARCH_MAX_WORKERS": {
        "label": "Số Luồng Tìm Kiếm",
        "description": "Số truy vấn tìm kiếm web chạy song song; tăng cao có thể nhanh hơn nhưng dễ gặp giới hạn dịch vụ.",
        "group": "ingestion",
        "type": "int",
        "default": 6,
        "min": 1,
        "max": 12,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "TARGETED_CRAWL_QUERIES_PER_CHAPTER": {
        "label": "Query Theo Chương",
        "description": "Số query bổ sung lấy từ từng chương sau khi duyệt đề cương.",
        "group": "ingestion",
        "type": "int",
        "default": 2,
        "min": 0,
        "max": 10,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "TARGETED_CRAWL_MAX_QUERIES": {
        "label": "Tổng Query Theo Đề Cương",
        "description": "Giới hạn tổng số query bổ sung lấy từ đề cương đã xác nhận.",
        "group": "ingestion",
        "type": "int",
        "default": 12,
        "min": 0,
        "max": 50,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "URL_FILTER_MAX_WORKERS": {
        "label": "Số Luồng Lọc URL",
        "description": "Số URL được kiểm tra content-type song song trước khi crawl.",
        "group": "ingestion",
        "type": "int",
        "default": 5,
        "min": 1,
        "max": 12,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAWL_MAX_WORKERS": {
        "label": "Số Luồng Crawl",
        "description": "Số trang nguồn được crawl song song; tăng cao có thể nhanh hơn nhưng tạo nhiều request mạng hơn.",
        "group": "ingestion",
        "type": "int",
        "default": 5,
        "min": 1,
        "max": 12,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAWL_MAX_SUB_LINKS": {
        "label": "Link Con Mỗi Trang",
        "description": "Số link nội bộ tối đa được crawl thêm từ mỗi trang nguồn.",
        "group": "ingestion",
        "type": "int",
        "default": 5,
        "min": 0,
        "max": 20,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAWL_MAX_ROOT_URLS": {
        "label": "Giới Hạn URL Gốc",
        "description": "Số URL hợp lệ tối đa được đưa vào deep crawl; đặt 0 để không giới hạn.",
        "group": "ingestion",
        "type": "int",
        "default": 0,
        "min": 0,
        "max": 200,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CRAWL_MAX_DEPTH2_LINKS": {
        "label": "Link Tầng 2 Mỗi Trang",
        "description": "Số link tầng 2 tối đa khi trang nguồn là trang điều hướng; đặt 0 để tắt crawl sâu tầng 2.",
        "group": "ingestion",
        "type": "int",
        "default": 3,
        "min": 0,
        "max": 10,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "MAX_CHUNKS_TO_EMBED": {
        "label": "Số Chunk Tối Đa Để Embedding",
        "description": "Giới hạn tổng số chunk được xử lý mỗi lần thu thập; bộ lọc heuristic sẽ giảm số này trước khi embedding.",
        "group": "ingestion",
        "type": "int",
        "default": 1000,
        "min": 100,
        "max": 5000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "EMBEDDING_BATCH_SIZE": {
        "label": "Kích Thước Batch Embedding",
        "description": "Số chunk gửi trong mỗi batch embedding; batch lớn thường nhanh hơn nhưng dùng nhiều tài nguyên hơn.",
        "group": "ingestion",
        "type": "int",
        "default": 200,
        "min": 20,
        "max": 1000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "CHROMADB_BATCH_SIZE": {
        "label": "Kích Thước Batch ChromaDB",
        "description": "Số chunk được ghi vào ChromaDB trong mỗi batch.",
        "group": "ingestion",
        "type": "int",
        "default": 100,
        "min": 10,
        "max": 1000,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },
    "MIN_SNIPPET_SCORE": {
        "label": "Điểm Snippet Tối Thiểu",
        "description": "Ngưỡng chất lượng snippet URL khi thu thập dữ liệu; URL dưới ngưỡng này bị bỏ qua.",
        "group": "ingestion",
        "type": "float",
        "default": 0.3,
        "min": 0.0,
        "max": 1.0,
        "user_editable": True,
        "admin_only": False,
        "sensitive": False,
    },

    # =========================================================================
    # GROUP: domain_caps — Giới Hạn Domain (chỉ admin)
    # =========================================================================
    "MAX_CHUNKS_PER_DOMAIN": {
        "label": "Giới Hạn Domain Cơ Bản",
        "description": "Số chunk tối đa mỗi domain khi không có giới hạn theo ngôn ngữ nào được áp dụng.",
        "group": "domain_caps",
        "type": "int",
        "default": 25,
        "min": 1,
        "max": 200,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "VI_DOMAIN_CAP": {
        "label": "Giới Hạn Domain Tiếng Việt",
        "description": "Số chunk tối đa mỗi domain cho nội dung tiếng Việt; cao hơn tiếng Anh vì nguồn tiếng Việt khan hiếm hơn.",
        "group": "domain_caps",
        "type": "int",
        "default": 80,
        "min": 10,
        "max": 500,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
    "EN_DOMAIN_CAP": {
        "label": "Giới Hạn Domain Tiếng Anh",
        "description": "Số chunk tối đa mỗi domain cho nội dung tiếng Anh.",
        "group": "domain_caps",
        "type": "int",
        "default": 35,
        "min": 5,
        "max": 300,
        "user_editable": False,
        "admin_only": True,
        "sensitive": False,
    },
}

# -------------------------------------------------------------------------
# Group metadata — labels and ordering for UI accordions
# -------------------------------------------------------------------------
PARAMETER_GROUPS: Dict[str, Dict[str, str]] = {
    "api_keys": {
        "label": "API Keys",
        "description": "Khóa truy cập và secret cho các dịch vụ ngoài; chỉ quản trị viên được chỉnh.",
    },
    "rate_limits": {
        "label": "API Rate Limit",
        "description": "Điều tiết request OpenAI khi local và host dùng chung API key.",
    },
    "rag": {
        "label": "RAG & Tìm Kiếm",
        "description": "Kiểm soát cách tài liệu được tìm kiếm và lọc từ cơ sở tri thức.",
    },
    "generation": {
        "label": "Tạo Nội Dung",
        "description": "Kiểm soát model LLM, số vòng chỉnh sửa và hành vi của writer.",
    },
    "ingestion": {
        "label": "Thu Thập & Phân Đoạn",
        "description": "Kiểm soát cách nội dung web được thu thập, phân đoạn và lập chỉ mục.",
    },
    "domain_caps": {
        "label": "Giới Hạn Domain",
        "description": "Giới hạn số chunk tối đa từ một domain duy nhất theo từng ngôn ngữ.",
    },
}


def get_user_registry() -> Dict[str, ParameterDef]:
    """Return only parameters that users are allowed to edit."""
    return {k: v for k, v in PARAMETER_REGISTRY.items() if v["user_editable"]}


def get_admin_registry() -> Dict[str, ParameterDef]:
    """Return all parameters (users + admin-only) for the admin panel."""
    return PARAMETER_REGISTRY


def get_defaults() -> Dict[str, Any]:
    """Return a flat dict of {param_key: default_value} for all parameters."""
    return {k: v["default"] for k, v in PARAMETER_REGISTRY.items()}
